### ISSUE TITLE
undefined string: htmlDateString

### ISSUE THREAD

**Issue by miklb** [miklb/michaelbishop#39]
Refactoring and reorganizing to finally upgrade to 3.0 and for some reason the filters aren't being added to Liquid.

I have tried:

- added a test filter
- explicitly add as a Liquid filter
- include filters in `eleventy.config.js` as opposed to a separate file

all with same result.

Something with modifying the library for `markdown-it-footnotes` ?

**Comment by mattl** [comment]
I can help take a look mid week if you don't figure it out by then.

**Comment by miklb** [comment]
I removed the filters and it seems the issue is broader than not loading the custom filters.

It doesn't seem like any of the `elventyConfig.addPlugin` calls are working.

`tag "metagen" not found but it's clearly in `eleventy.config.js`

**Comment by miklb** [comment]
@mattl I found it. Somehow I had named `eleventy.config.js` `.eleventy.config.js` and that extra `.` makes a big difference it turns out™.
